- name: install apache & php packages for Ubuntu
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"


- name: copy default html file for site
  tags:  apache,apache2
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: start apache (Ubuntu)
  tags: apache, Ubuntu
  service:
    name: apache2
    state: started
    enabled: true
  when: ansible_distribution == "Ubuntu"
